###
GET http://localhost:8080/abteilungen
Content-Type: */*
###
GET http://localhost:8080/abteilungen/1
###

POST http://localhost:8080/abteilungen
Content-Type: application/json

{
"nickname":"WI",
"name":"Wirtschaftsingenieure"
}

###

PUT http://localhost:8080/abteilungen/1
Content-Type: application/json

{
  "name": "Wirtschaftler"
}

###

DELETE http://localhost:8080/abteilungen/1