###
GET http://localhost:8080/abteilung
Content-Type: */*
###
GET http://localhost:8080/abteilung/1
###

POST http://localhost:8080/abteilung
Content-Type: application/json

{
"nickname":"WI",
"name":"Wirtschaftsingenieure"
}

###

PUT http://localhost:8080/abteilung/1
Content-Type: application/json

{
  "name": "Maschinenbau"
}

###

DELETE http://localhost:8080/abteilung/1