###
GET http://localhost:8080/buildings
###
GET http://localhost:8080/buildings/1
###

POST http://localhost:8080/buildings
Content-Type: application/json

{
"name":"TestGeb",
"kuerzel":"T"
}

###

PUT http://localhost:8080/buildings/1
Content-Type: application/json

{
  "name": "Geb___changed"
}

###

DELETE http://localhost:8080/buildings/1