#1
DELETE http://localhost:8080/abteilungen/all
###2
DELETE http://localhost:8080/buildings/all
###3
DELETE http://localhost:8080/lesson-starts/all
###4
DELETE http://localhost:8080/lesson-ends/all
###5
DELETE http://localhost:8080/tags/all
###6
DELETE http://localhost:8080/teachers/all
###7
DELETE http://localhost:8080/groups/all
###8
DELETE http://localhost:8080/jahrgaenge/all
###9
DELETE http://localhost:8080/lessons/all
###10
DELETE http://localhost:8080/rooms/all
###11
DELETE http://localhost:8080/schulklassen/all
###12
DELETE http://localhost:8080/students/all
###13
DELETE http://localhost:8080/subjects/all
###14
POST http://localhost:8080/abteilungen
Content-Type: application/json

{
  "nickname":"WI",
  "name":"Wirtschaftsingenieure"
}
###8
POST http://localhost:8080/abteilungen
Content-Type: application/json

{
  "nickname":"IT",
  "name":"Informationstechnologie"
}
###9
POST http://localhost:8080/abteilungen
Content-Type: application/json

{
  "nickname":"ME",
  "name":"Maschinenbau"
}
###10
POST http://localhost:8080/abteilungen
Content-Type: application/json

{
  "nickname":"BWL",
  "name":"Betriebswirtschaftslehre"
}
###11
GET http://localhost:8080/abteilungen
###12
POST http://localhost:8080/buildings
Content-Type: application/json

{
  "name":"Anichstraße",
  "kuerzel":"A"
}
###13
POST http://localhost:8080/buildings
Content-Type: application/json

{
  "name":"Innrain",
  "kuerzel":"I"
}
###14
POST http://localhost:8080/buildings
Content-Type: application/json

{
  "name":"Stoeckl",
  "kuerzel":"S"
}
###15
POST http://localhost:8080/buildings
Content-Type: application/json

{
  "name":"Hofueberbau",
  "kuerzel":"H"
}
###16
GET http://localhost:8080/buildings
###17
POST http://localhost:8080/lesson-starts
Content-Type: application/json

{
  "lessonNumber": 1,
  "time": "08:00:00"
}
###18
POST http://localhost:8080/lesson-starts
Content-Type: application/json

{
  "lessonNumber": 2,
  "time": "08:50:00"
}
###19
POST http://localhost:8080/lesson-starts
Content-Type: application/json

{
  "lessonNumber": 3,
  "time": "09:55:00"
}
###20
POST http://localhost:8080/lesson-starts
Content-Type: application/json

{
  "lessonNumber": 4,
  "time": "10:45:00"
}
###21
GET http://localhost:8080/lesson-starts
###22
POST http://localhost:8080/lesson-ends
Content-Type: application/json

{
  "lessonNumber": 1,
  "time": "08:50:00"
}
###23
POST http://localhost:8080/lesson-ends
Content-Type: application/json

{
  "lessonNumber": 2,
  "time": "09:40:00"
}
###24
POST http://localhost:8080/lesson-ends
Content-Type: application/json

{
  "lessonNumber": 3,
  "time": "10:45:00"
}
###25
GET http://localhost:8080/lesson-ends/
###26
POST http://localhost:8080/tags
Content-Type: application/json

{
  "name": "Fraesen"
}
###27
POST http://localhost:8080/tags
Content-Type: application/json

{
  "name": "Drehen"
}
###28
POST http://localhost:8080/tags
Content-Type: application/json

{
  "name": "Bohren"
}
###29
POST http://localhost:8080/tags
Content-Type: application/json

{
  "name": "Feilen"
}
###30
POST http://localhost:8080/tags
Content-Type: application/json

{
  "name": "Stanzen"
}
###31
GET http://localhost:8080/tags/
###32
POST http://localhost:8080/teachers
Content-Type: application/json

{
  "nickname": "MustM",
  "firstname": "Max",
  "lastname": "Mustermann",
  "tags": [
    {
      "id": 1,
      "name": "Stanzen"
    },
    {
      "id": 2,
      "name": "Bohren"
    }
  ]
}
###33
POST http://localhost:8080/teachers
Content-Type: application/json

{
  "nickname": "MeisR",
  "firstname": "Raphael",
  "lastname": "Meister"
}
###34
POST http://localhost:8080/teachers
Content-Type: application/json

{
  "nickname": "BaumJ",
  "firstname": "Josef",
  "lastname": "Baum"
}
###35
POST http://localhost:8080/teachers
Content-Type: application/json

{
  "nickname": "WinkG",
  "firstname": "Günther",
  "lastname": "Winkler"
}
###36
POST http://localhost:8080/teachers
Content-Type: application/json

{
  "nickname": "LangT",
  "firstname": "Thomas",
  "lastname": "Lang"
}
###37
GET http://localhost:8080/teachers
###38
POST http://localhost:8080/groups
Content-Type: application/json

{
"kennung": "A"
 }
###39
POST http://localhost:8080/jahrgaenge
Content-Type: application/json

{
  "stufe": 1
}
###40
GET http://localhost:8080/jahrgaenge