### GET All LessonEnds
GET http://localhost:8080/lesson-ends
Content-Type: */*
###

### GET LessonEnd by ID
GET http://localhost:8080/lesson-ends/1
Content-Type: */*
###

### POST Create a LessonEnd
POST http://localhost:8080/lesson-ends
Content-Type: application/json

{
  "lessonNumber": 1,
  "time": "10:00:00"
}
###

### PUT Update a LessonEnd
PUT http://localhost:8080/lesson-ends/1
Content-Type: application/json

{
  "lessonNumber": 2,
  "time": "11:00:00"
}
###

### DELETE LessonEnd by ID
DELETE http://localhost:8080/lesson-ends/1
Content-Type: */*
###
